### ISSUE TITLE
Some import issues

### ISSUE THREAD

**Issue by Ottovonxu** [twistedcubic/learn-to-hash#2]
Hi
Thanks for sharing the code!  I ran the code and have the following questions

1. in demo_train.py, the default dataset name is null. And the code pointed to a function named utils.load_data.  May I ask if load_data() can be posted?    
2. in kmkahip.py, the code "import logreg". May I ask if logreg can be shared?

**Comment by twistedcubic** [comment]
Hi, thanks for spotting that `logreg.py` is missing. I added the script to the repo. 

For `load_data()`, the function has been [renamed here](https://github.com/twistedcubic/learn-to-hash/blob/master/utils.py#L266) to `load_data_dep()`, it can be be called if you have a custom dataset to load. The dataset loading is done with functions such as `load_glove_data()` [here](https://github.com/twistedcubic/learn-to-hash/blob/master/utils.py#L281), the data, e.g. Glove data, should live in a directory whose path is specified by `glove_dir` in the config file, as in the Readme.
